# Generated by Django 6.0.6 on 2026-07-05 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='documentos/', verbose_name='Archivo')),
                ('hash_sha256', models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('esta_firmado', models.BooleanField(default=False, verbose_name='¿Está firmado?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
