# Generated by Django 5.2.12 on 2026-07-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('documentacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificado', verbose_name='Certificado usado'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de firma'),
        ),
        migrations.AddField(
            model_name='documento',
            name='firma_sha256',
            field=models.TextField(blank=True, verbose_name='Firma SHA-256'),
        ),
    ]
