# Generated by Django 5.2.12 on 2026-07-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('archivo_cer', models.FileField(upload_to='certificados/cer/')),
                ('archivo_key', models.FileField(upload_to='certificados/key/')),
                ('numero_serie', models.CharField(blank=True, max_length=255)),
                ('subject', models.TextField(blank=True)),
                ('issuer', models.TextField(blank=True)),
                ('rfc', models.CharField(blank=True, max_length=20)),
                ('curp', models.CharField(blank=True, max_length=30)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('algoritmo_firma', models.CharField(blank=True, max_length=255)),
                ('huella_sha256', models.CharField(blank=True, max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
=======
>>>>>>> main
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
